[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "abstract-backend"
version = "0.0.0"
description = "ðŸ§‘â€ðŸ« A library as an abstract layer to rule BackEnd side components and support it as Python plugin features."
authors = [{ name = "Chisanan232", email = "chi10211201@cycu.org.tw" }]
requires-python = ">=3.12,<4.0"
readme = "README.md"
license = { file = "LICENSE" }
keywords = []
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Utilities",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/Chisanan232/abstract-backend"
Repository = "https://github.com/Chisanan232/abstract-backend"
Documentation = "https://chisanan232.github.io/abstract-backend/"
Changelog = "https://chisanan232.github.io/abstract-backend/docs/next/changelog"
"Project Management" = "https://app.clickup.com/9018752317/v/f/90189305252/90184991515"

[dependency-groups]
dev = [
    "pytest>=8.4.1,<9",
    "pytest-cov>=6.2.1,<8",
    "coverage>=7.9.2,<8",
    "pytest-rerunfailures>=15.1,<17",
    "aiohttp>=3.12.13,<4",
    "pytest-asyncio>=1.0.0,<2",
    "python-dotenv>=1.1.1,<2",
]
pre-commit-ci = [
    "pre-commit>=4.2.0,<5",
    "pylint>=3.3.7,<5",
    "mypy>=1.16.1,<2",
]

[tool.uv]
default-groups = [
    "dev",
    "pre-commit-ci",
]

[tool.hatch.build.targets.sdist]
include = ["abe/"]
packages = ["abe"]
artifacts = ["abe/py.typed"]

[tool.hatch.build.targets.wheel]
include = ["abe/"]
packages = ["abe"]
artifacts = ["abe/py.typed"]
